import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#ffffff' },
  container: { flex: 1, paddingHorizontal: 16, paddingTop: 8 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingTop: 60, paddingBottom: 4 },
  heading: { fontSize: 22, fontWeight: '500', color: '#000' },
  subheading: { fontSize: 12, color: '#888', marginTop: 2 },
  avatarRow: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#fff' },
  avatarText: { fontSize: 9, fontWeight: '500' },
  summaryRow: { flexDirection: 'row', gap: 7, marginTop: 16, marginBottom: 14 },
  summaryCard: { flex: 1, backgroundColor: '#f5f5f3', borderRadius: 10, padding: 11 },
  summaryLabel: { fontSize: 10, color: '#888', marginBottom: 3 },
  summaryVal: { fontSize: 16, fontWeight: '500', color: '#000' },
  green: { color: '#0f6e35' },
  amber: { color: '#854F0B' },
  progressTrack: { height: 4, backgroundColor: '#f0f0ee', borderRadius: 2, marginBottom: 20, overflow: 'hidden' },
  progressFill: { height: 4, backgroundColor: '#1D9E75', borderRadius: 2 },
  sectionLabel: { fontSize: 10, fontWeight: '500', color: '#aaa', letterSpacing: 0.8, marginBottom: 10 },
  bill: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 0.5, borderColor: '#e8e8e8', borderRadius: 12, padding: 12, marginBottom: 8 },
  billPaid: { opacity: 0.45 },
  check: { width: 18, height: 18, borderRadius: 9, borderWidth: 1.5, borderColor: '#ddd', alignItems: 'center', justifyContent: 'center' },
  checkDone: { backgroundColor: '#1D9E75', borderColor: '#1D9E75' },
  checkMark: { color: '#fff', fontSize: 10, fontWeight: '500' },
  billIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  billIconText: { fontSize: 15 },
  billInfo: { flex: 1 },
  billName: { fontSize: 13, fontWeight: '500', color: '#000' },
  billMeta: { fontSize: 10, color: '#999', marginTop: 1 },
  billRight: { alignItems: 'flex-end' },
  billAmt: { fontSize: 13, fontWeight: '500', color: '#000' },
  stPaid: { fontSize: 10, color: '#0F6E56', marginTop: 1 },
  stDue: { fontSize: 10, color: '#854F0B', marginTop: 1 },
  eachAmt: { fontSize: 10, color: '#bbb', marginTop: 1 },
  addBtn: { borderWidth: 0.5, borderColor: '#ddd', borderStyle: 'dashed', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 4 },
  addBtnText: { fontSize: 13, color: '#999' },
  nav: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 10, borderTopWidth: 0.5, borderTopColor: '#eee', backgroundColor: '#fff' },
  navItem: { alignItems: 'center', gap: 3 },
  navDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#1D9E75' },
  navIcon: { fontSize: 14, color: '#ccc' },
  navLabel: { fontSize: 10, color: '#aaa' },
  navActive: { color: '#0F6E56', fontWeight: '500' },
});